sudo: enabled 

before_install: 
- sudo apt-get install libgtest-dev
- sudo apt-get install cmake
- cd /usr/src/gtest
- sudo cmake CMakelists.txt


language: cpp

compiler: gcc

script: 
- make clean
- make
- ./TicTacToeBoardTest
